name: 'Deploy to Cloudflare Workers'
description: 'Deploy to Cloudflare Workers'
inputs:
  internal_api_url:
    description: 'Internal API URL'
    required: true
  internal_api_key:
    description: 'Interal API Key'
    required: true
  github_token:
    description: 'Github token for NPM install'
    required: true
  cf_token:
    description: 'Cloudflare API token for wrangler publish'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.internal_api_url }}
    - ${{ inputs.internal_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.cf_token }}
