language: node_js
node_js:
- 6.10.3
before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip"
    -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
cache:
  directories:
  - "$HOME/.yarn-cache"
install:
- yarn install --frozen-lockfile
script:
- yarn build
- yarn lint
- yarn test
- yarn install-production-dependencies
- yarn package
- yarn terraform-init
- yarn terraform-plan
deploy:
- provider: script
  skip_cleanup: true
  script:
  - yarn terraform-apply
  - yarn upload-frontend
  on:
    repo: jschr/VSCodeThemes
    branch: production
