version: '3'

services:
  db:
    image: ghcr.io/vscodethemes/db:main
    ports:
      - 5432:5432

  api:
    image: ghcr.io/vscodethemes/api:main
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DATABASE_URL=postgresql://local:local@db:5432/vscodethemes-local

  kv:
    image: ghcr.io/vscodethemes/kv:main
    ports:
      - 6379:6379
